steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:0.12.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "terraform" ]; then
        cd terraform 
        terraform init
      else
        for dir in environments/*/
        do 
          cd ${dir}
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init || exit 1
          cd ../../
        done
      fi 

- id: 'tf fmt'
  name: 'hashicorp/terraform:0.12.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd terraform 
      terraform fmt

- id: 'tf validate'
  name: 'hashicorp/terraform:0.12.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd terraform 
      terraform validate

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:0.12.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "terraform" ]; then
        cd terraform 
        terraform apply -auto-approve
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
        echo "*******************************************************************************"
      fi
# [END tf-apply]      
