steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:0.12.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "terraform" ]; then
        for dir in $(find terraform -maxdepth 1 -type d -regex '^./[a-zA-Z].*' | cut -f 2 -d "/")
        do 
          cd terraform/${dir}
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init || exit 1
          cd ../../
        done
      fi 

- id: 'tf fmt'
  name: 'hashicorp/terraform:0.12.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd terraform 
      terraform fmt

- id: 'tf validate'
  name: 'hashicorp/terraform:0.12.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd terraform 
      terraform validate

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.12.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ -d "terraform" ]; then
        for dir in $(find terraform -maxdepth 1 -type d -regex '^./[a-zA-Z].*' | cut -f 2 -d "/")
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}  
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform plan || exit 1
          cd ../../
        done
      fi 
# [END tf-plan]

