name: Terraform Diff-Sync

on: 
  pull_request:
    branches: 
    - master

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: donkomura/TerraformPractice/terraform@master
    - name: Terraform Init
      if: github.event_name == 'pull_request' && github.ref != 'apply'
      uses: hashicorp/terraform-github-actions/init@master

  plan:
    runs-on: ubuntu-latest
    steps:
    - uses: donkomura/TerraformPractice/terraform@master
    - name: Terraform Plan
      if: github.event_name == 'pull_request' && github.ref != 'apply'
      uses: hashicorp/terraform-github-actions/plan@master

  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: donkomura/TerraformPractice/terraform@master
    - name: Terraform Apply
      if: github.event_name == 'pull_request' && github.ref == 'apply'
      uses: hashicorp/terraform-github-actions/apply@master
      with:
        entrypoint: script/tf_apply.sh
