name: Terraform Diff-Sync

on: 
  pull_request:
    branches: 
    - master

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - name: Terraform Init
      if: github.event_name == 'pull_request' && github.ref != 'apply'
      uses: docker://hashicorp/terraform:0.12.6
      with:
        entrypoint: sh
          args:
          - '-c'
          - |
              if [ -d "environments/$GITHUB_HEAD_REF/" ]; then
                cd environments/$GITHUB_REF_HEAD
                terraform init
              else
                for dir in environments/*/
                do
                  cd ${dir}
                  env=${dir%*/}
                  env=${env#*/}
                  echo ""
                  echo "*************** TERRAFORM INIT ******************"
                  echo "******* At environment: ${env} ********"
                  echo "*************************************************"
                  terraform init || exit 1
                  cd ../../
                done
              fi
  
  plan:
     runs-on: ubuntu-latest
    steps:
    - name: Terraform Plan
      if: github.event_name == 'pull_request' && github.ref != 'apply'
      uses: docker://hashicorp/terraform:0.12.6
      with:
        entrypoint: sh
          args:
    args: 
    - '-c'
    - | 
        if [ -d "environments/$GITHUB_REF_HEAD/" ]; then
          cd environments/$GITHUB_REF_HEAD
          terraform plan
        else
          for dir in environments/*/
          do 
            cd ${dir}   
            env=${dir%*/}
            env=${env#*/}  
            echo ""
            echo "*************** TERRAFOM PLAN ******************"
            echo "******* At environment: ${env} ********"
            echo "*************************************************"
            terraform plan || exit 1
            cd ../../
          done
        fi 
  apply:
     runs-on: ubuntu-latest
    steps:
    - name: Terraform Apply
      if: github.event_name == 'pull_request' && github.ref == 'apply'
      uses: docker://hashicorp/terraform:0.12.6
      with:
        entrypoint: sh
          args:
    args: 
    - '-c'
    - | 
        if [ -d "environments/$GITHUB_REF_HEAD/" ]; then
          cd environments/$GITHUB_REF_HEAD
          terraform apply -auto-approve
        else
          echo "***************************** SKIPPING APPLYING *******************************"
          echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
          echo "*******************************************************************************"
        fi
