name: Terraform Diff-Sync

on: 
  pull_request:
    branches: 
    - master

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: ./
    - name: Terraform Init
      if: github.event_name == 'pull_request' && github.ref != 'apply'
      uses: docker://hashicorp/terraform:0.12.6
      with:
        entrypoint: script/tf_init.sh

  plan:
    runs-on: ubuntu-latest
    steps:
    - uses: ./
    - name: Terraform Plan
      if: github.event_name == 'pull_request' && github.ref != 'apply'
      uses: docker://hashicorp/terraform:0.12.6
      with:
       entrypoint: script/tf_plan.sh

  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: ./
    - name: Terraform Apply
      if: github.event_name == 'pull_request' && github.ref == 'apply'
      uses: docker://hashicorp/terraform:0.12.6
      with:
        entrypoint: script/tf_apply.sh
