name: Terraform Diff-Sync

on: 
  pull_request:
    branches: 
    - master

jobs:
  on-pull-request:
    name: On Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Filter to PR Opened
      uses: actions/bin/filter@master
      with:
        args: "action 'opened|synchronize|rerequested'"

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform - Format
      uses: hashicorp/terraform-github-actions/fmt@v0.4.0
      env:
        TF_ACTION_WORKING_DIR: "./terraform"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions/init@0.4.0
      env:
        TF_ACTION_WORKING_DIR: "./terraform"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Terraform - Validate
      uses: hashicorp/terraform-github-actions/validate@v0.4.0
      env:
        TF_ACTION_WORKING_DIR: "./terraform"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Terraform - Plan
      uses: hashicorp/terraform-github-actions/plan@v0.4.0
      env:
        TF_ACTION_WORKING_DIR: "./terraform"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
